spring:
  application:
    name: book-store
  datasource:
    url: jdbc:postgresql://localhost:5432/imagine
    username: postgres
    password: postgres
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /${spring.application.name}